# Generated by Django 6.0 on 2025-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0002_alter_product_options_remove_product_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="memory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="resolution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="screen_diagonal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
