# Generated by Django 6.0 on 2025-12-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parser_app",
            "0003_product_url_alter_product_color_alter_product_memory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number_of_reviews",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
